### ISSUE TITLE
공통 모달 컴포넌트

### ISSUE THREAD

**Issue by kdongha** [INSPJT/instagram_clone_frontend#7]
![image.png](https://images.zenhubusercontent.com/5f45c34298f31a25fb68e335/07197a76-29b2-44a2-8e00-b1649914e216)
해당 이미지처럼 뒷배경 딤드처리, 스크롤 금지 처리에 사용할 모달이 필요 합니다.

**Comment by Dinoryong** [comment]
now working on it/...

**Comment by haeunkim428** [comment]
머지 되었습니다
