### ISSUE TITLE
케러셀 컴포넌트

### ISSUE THREAD

**Issue by kdongha** [INSPJT/instagram_clone_frontend#8]
이미지 슬라이드를 위한 캐러셀이 필요합니다.

- [x] 이미지 크기에 상관없이 컨테이너 크기에 맞춘 이미지 캐러셀
- [x] 좌측, 우측 이동 버튼
- [x] 1번 이미지의 경우 좌측버튼 숨김, 마지막 이미지의 경우 우측버튼 숨김
- [x] 현재 위치를 알수있는 Dots

**Comment by Dinoryong** [comment]
now working on it/...

**Comment by kdongha** [comment]
@Dinoryong @haeunkim428 @HyeonHak 캐러셀 기본만 구현했습니다.
크기정해야 할것 같고, 부가기능 필요한게 있을까요?

**Comment by HyeonHak** [comment]
@kdongha 
오른쪽 상단에 사진 갯수를 보여주는 부분이 필요합니다 ex) 3/5

**Comment by kdongha** [comment]
@HyeonHak 동영상은 일단 제외하기로 해서 나중에 하겠습니다.
모바일 웹으로 볼때 오른쪽 상단에 사진갯수 안보이고 하단에 도트로 인덱스 표시하지 않나요?

**Comment by HyeonHak** [comment]
@kdongha 
앱의 경우는 사진갯수 + 도트 
웹의 경우는 도트만 나오기는 합니다.
핵심 기능은 아니니 꼭 필요하진 않겠지만, 도트가 여러개 일 경우 가독성을 위해 있는게 좋지 않겠습니까!

**Comment by haeunkim428** [comment]
@kdongha 
도트 구현한다하면 전체 사진 개수랑 지금 보고 있는 인덱스 정보 있기는 할테니
숫자 인덱스도 추가해도 좋을거 같습니당

**Comment by Dinoryong** [comment]
도트 필요 ,

**Comment by kdongha** [comment]
@Dinoryong 
도트는 아래에 상태바쪽에 넣으면 될꺼같아서 캐러셀에서는 뻇습니다.

**Comment by kdongha** [comment]
@Dinoryong Dots도 추가했습니다~
